services:
  backend:
    build:
      context: ./backend
    container_name: job-mng-backend
    working_dir: /app
    ports:
      - "5050:5050"
    environment:
      PORT: 5050
      DATABASE_URL: ./job-mng-system.sqlite
      JWT_SECRET: job_mng_system_demo_secret
    volumes:
      - ./backend:/app
      - backend_node_modules:/app/node_modules

  frontend:
    build:
      context: ./frontend
    container_name: job-mng-frontend
    working_dir: /app
    depends_on:
      - backend
    ports:
      - "5173:5173"
    environment:
      VITE_API_BASE_URL: http://localhost:5050/api
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules

volumes:
  backend_node_modules:
  frontend_node_modules:
